apiVersion: v2
name: ska-mid-cbf-fhs-vcc-boogie
description: A Helm chart for deploying boogie
version: 0.3.3
appVersion: 0.3.3
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
